version: '3.8'

services:
  db:
    image: postgres:13
    container_name: cuadros_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - traefik

  backend:
    build: ./cuadros-back
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`marinacuadros.duckdns.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=duckdns"
      - "traefik.http.routers.backend.tls=true"
       # Opcional: si necesitas quitar el prefijo /api antes de llegar al backend
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
    container_name: cuadros_backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - traefik

  frontend:
    build: ./cuadros-front
    container_name: cuadros_frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cuadros-http.rule=Host(`marinacuadros.duckdns.org`)" #Dominio de la pagina
      - "traefik.http.routers.cuadros-http.entrypoints=web"
      - "traefik.http.routers.cuadros-https.tls=true"
      - "traefik.http.routers.cuadros-https.tls.certresolver=duckdns"
      - "traefik.http.routers.cuadros-https.entrypoints=websecure"
      - "traefik.http.routers.cuadros-https.rule=Host(`marinacuadros.duckdns.org`)" #Dominio de la pagina
    networks:
      - traefik

volumes:
  pg_data:


networks:
  traefik:
    external: true
