version: '3.8'

services:
  db:
    image: postgres:13
    container_name: cuadros_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./cuadros-back
    container_name: cuadros_backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./cuadros-front
    container_name: cuadros_frontend
    ports:
      - "80:80"

volumes:
  pg_data:


