name: CI/CD Deploy to NUC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1) Trae el código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Entra a tu carpeta y actualiza
      - name: Pull latest & rebuild
        working-directory: /home/bruno/proyectos/cuadros
        run: |
          git pull origin main
          docker compose build --no-cache
          docker compose up -d
